version: '2'

services:
  addok:
    image: addok
    container_name: addok
    build:
      dockerfile: Dockerfile
      context: ./addok
    ports:
    - "7878:7878"
    volumes:
    - /data/addok.conf:/etc/addok/addok.conf
    - /data/addok.db:/data/addok.db
    - ./logs:/logs
    links:
    - addok-redis:redis
    environment:
      WORKERS: 1
      WORKER_TIMEOUT: 30
      LOG_QUERIES: 1
      LOG_NOT_FOUND: 1
      SLOW_QUERIES: 200
  addok-redis:
    image: etalab/addok-redis
    container_name: addok-redis
    volumes:
    - /data/dump.rdb:/data/dump.rdb
