version: '2'
services:
  addok-ban:
    image: etalab/addok
    ports:
    - "7878:7878"
    volumes:
    - ./addok-data-ban/addok.conf:/etc/addok/addok.conf
    - ./addok-data-ban/addok.db:/data/addok.db
    - ./logs:/logs
    links:
    - addok-redis-ban:redis
    environment:
      WORKERS: 1
      WORKER_TIMEOUT: 30
      LOG_QUERIES: 1
      LOG_NOT_FOUND: 1
      SLOW_QUERIES: 200
  addok-redis-ban:
    image: etalab/addok-redis
    volumes:
    - ./addok-data-ban/dump.rdb:/data/dump.rdb
  addok-bano:
    image: etalab/addok
    ports:
    - "7879:7878"
    volumes:
    - ./addok-data-bano/addok.conf:/etc/addok/addok.conf
    - ./addok-data-bano/addok.db:/data/addok.db
    - ./logs-bano:/logs
    links:
    - addok-redis-bano:redis
    environment:
      WORKERS: 1
      WORKER_TIMEOUT: 30
      LOG_QUERIES: 1
      LOG_NOT_FOUND: 1
      SLOW_QUERIES: 200
  addok-redis-bano:
    image: etalab/addok-redis
    volumes:
    - ./addok-data-bano/dump.rdb:/data/dump.rdb
  addok-poi:
    image: etalab/addok
    ports:
    - "7880:7878"
    volumes:
    - ./addok-data-poi/addok.conf:/etc/addok/addok.conf
    - ./addok-data-poi/addok.db:/data/addok.db
    - ./logs-poi:/logs
    links:
    - addok-redis-poi:redis
    environment:
      WORKERS: 1
      WORKER_TIMEOUT: 30
      LOG_QUERIES: 1
      LOG_NOT_FOUND: 1
      SLOW_QUERIES: 200
  addok-redis-poi:
    image: etalab/addok-redis
    volumes:
    - ./addok-data-poi/dump.rdb:/data/dump.rdb
